# Generated by Django 6.0.2 on 2026-02-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filiere', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nom_filiere', models.CharField(max_length=150)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=10)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'db_table': 'filieres',
                'ordering': ['niveau', 'nom_filiere'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=50, unique=True)),
                ('capacite', models.IntegerField(default=30)),
                ('batiment', models.CharField(blank=True, default='', max_length=100)),
                ('nb_projecteurs', models.IntegerField(default=0, verbose_name='Nombre de projecteurs')),
                ('nb_rallonges', models.IntegerField(default=0, verbose_name='Nombre de rallonges')),
                ('nb_ordinateurs', models.IntegerField(default=0, verbose_name="Nombre d'ordinateurs")),
                ('nb_chargeurs', models.IntegerField(default=0, verbose_name='Nombre de chargeurs')),
                ('nb_adaptateurs', models.IntegerField(default=0, verbose_name="Nombre d'adaptateurs")),
                ('verrouille', models.BooleanField(default=False, verbose_name='Verrouillé (modification nécessite accord directeur)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'db_table': 'salles',
                'ordering': ['nom_salle'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cours', models.CharField(db_index=True, max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('credit', models.IntegerField(default=3)),
                ('volume_horaire', models.IntegerField(default=0, verbose_name='Volume horaire (heures)')),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Suspendu', 'Suspendu')], default='Actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='gestion1.filiere')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'cours',
                'ordering': ['code_cours'],
            },
        ),
    ]
