# Generated by Django 6.0.2 on 2026-02-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 ★ - Très mécontent'), (2, '2 ★ - Mécontent'), (3, '3 ★ - Neutre'), (4, '4 ★ - Satisfait'), (5, '5 ★ - Très satisfait')])),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire (optionnel)')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email (optionnel)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_traite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedbacks',
                'ordering': ['-date_creation'],
            },
        ),
    ]
