# Generated by Django 6.0.2 on 2026-02-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directeur', '0001_initial'),
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Present', 'Présent'), ('Absent', 'Absent'), ('Retard', 'Retard'), ('Excuse', 'Excusé')], max_length=10)),
                ('date_pointage', models.DateField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='directeur.emploidutemps')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='etudiant.etudiant')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'presences',
                'unique_together': {('creneau', 'etudiant', 'date_pointage')},
            },
        ),
    ]
