# Generated by Django 6.0.2 on 2026-02-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='ID Utilisateur')),
                ('nom_utilisateur', models.CharField(default='', max_length=100)),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION_USER', 'Création utilisateur'), ('MODIFICATION_USER', 'Modification utilisateur'), ('SUPPRESSION_USER', 'Suppression utilisateur'), ('VALIDATION_NOTE', 'Validation note'), ('CREATION_EDT', 'Création EDT'), ('MODIFICATION_EDT', 'Modification EDT'), ('IMPORT_NOTES', 'Import notes'), ('EXPORT', 'Export rapport'), ('MODIFICATION', 'Modification')], max_length=50)),
                ('table_affectee', models.CharField(blank=True, default='', max_length=50)),
                ('id_enregistrement', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Log d'Audit",
                'verbose_name_plural': "Logs d'Audit",
                'db_table': 'audit_log',
                'ordering': ['-date_action'],
            },
        ),
    ]
