# Generated by Django 6.0.2 on 2026-02-23 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('telephone_secondaire', models.CharField(blank=True, default='', max_length=20, verbose_name='Deuxième numéro')),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'db_table': 'parents',
            },
        ),
        migrations.CreateModel(
            name='LiaisonParentEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_parente', models.CharField(choices=[('Père', 'Père'), ('Mère', 'Mère'), ('Tuteur', 'Tuteur'), ('Tutrice', 'Tutrice'), ('Autre', 'Autre')], max_length=20)),
                ('date_liaison', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaisons_parent', to='etudiant.etudiant')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaisons', to='parent.parent')),
            ],
            options={
                'verbose_name': 'Liaison Parent-Étudiant',
                'db_table': 'liaison_parent_etudiant',
                'unique_together': {('parent', 'etudiant')},
            },
        ),
    ]
