# Generated by Django 6.0.2 on 2026-02-24 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_evenement', models.CharField(choices=[('EVENEMENT', 'Événement'), ('VIDEO', 'Vidéo'), ('ANNONCE', 'Annonce'), ('ACTUALITE', 'Actualité'), ('ALERTE', 'Alerte')], default='EVENEMENT', max_length=20, verbose_name='Type')),
                ('url_video', models.URLField(blank=True, default='', verbose_name='URL Vidéo (YouTube, Vimeo...)')),
                ('date_evenement', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('lieu', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name='Image de couverture')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('est_urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'evenements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Image')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('est_accueil', models.BooleanField(default=False, verbose_name="Afficher sur la page d'accueil")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'publications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
