# Generated by Django 6.0.2 on 2026-02-23 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignant', '0001_initial'),
        ('gestion1', '0001_initial'),
        ('gestion2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_creneau', models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('TP', 'TP'), ('Examen', 'Examen')], default='Cours', max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_edt', to='gestion1.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_edt', to='enseignant.enseignant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_edt', to='gestion1.salle')),
            ],
            options={
                'verbose_name': 'Créneau EDT',
                'verbose_name_plural': 'Emplois du Temps',
                'db_table': 'emploi_du_temps',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='ValidationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='Valide', max_length=20)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='gestion2.note')),
                ('validateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation de Note',
                'db_table': 'validation_notes',
                'ordering': ['-date_validation'],
            },
        ),
    ]
