# Generated by Django 6.0.2 on 2026-02-23 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
        ('gestion1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=10)),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('total_credits', models.IntegerField(blank=True, null=True)),
                ('chemin_pdf', models.CharField(blank=True, default='', max_length=255)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='etudiant.etudiant')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'db_table': 'bulletins',
                'ordering': ['-annee_academique', '-semestre'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_note', models.FloatField()),
                ('type_evaluation', models.CharField(choices=[('Examen', 'Examen'), ('Controle', 'Contrôle'), ('TP', 'TP'), ('TD', 'TD'), ('Projet', 'Projet'), ('Devoir', 'Devoir')], default='Examen', max_length=20)),
                ('statut_validation', models.CharField(choices=[('En attente', 'En attente'), ('Valide', 'Validé'), ('Rejete', 'Rejeté')], db_index=True, default='En attente', max_length=20)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion1.cours')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiant.etudiant')),
                ('id_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ['-date_saisie'],
            },
        ),
    ]
